# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdyhhCqlAAskVKPZ2dqbcumIDaVpk3oq
"""

!pip install tensorflow pandas numpy

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense
from tensorflow.keras.models import Model

!git clone https://github.com/SaiPriya9017/Low_Resource_Language_Translation.git

df1 = pd.read_csv("Low_Resource_Language_Translation/banjara_language_words.csv")
df2 = pd.read_csv("Low_Resource_Language_Translation/sentences.csv")

df = pd.concat([df1, df2], ignore_index=True)
print("Total rows:", len(df))

inputs = []
targets = []

for _, row in df.iterrows():
    eng = row["English"]
    banj = row["Banjara"]

    if pd.isna(eng) or pd.isna(banj):
        continue

    eng = str(eng).lower().strip()
    banj = str(banj).lower().strip()

    inputs.append("<2banj> <start> " + eng)
    targets.append(banj + " <end>")

    inputs.append("<2eng> <start> " + banj)
    targets.append(eng + " <end>")

tokenizer = Tokenizer(filters="")
tokenizer.fit_on_texts(inputs + targets)

vocab_size = len(tokenizer.word_index) + 1
print("Vocab size:", vocab_size)

encoder_seq = tokenizer.texts_to_sequences(inputs)
decoder_seq = tokenizer.texts_to_sequences(targets)

max_len = max(
    max(len(x) for x in encoder_seq),
    max(len(x) for x in decoder_seq)
)

encoder_input = pad_sequences(encoder_seq, maxlen=max_len, padding="post")
decoder_output = pad_sequences(decoder_seq, maxlen=max_len, padding="post")

decoder_input_seq = []
decoder_target_seq = []

for t in targets:
    seq = tokenizer.texts_to_sequences([t])[0]
    decoder_input_seq.append(seq[:-1])
    decoder_target_seq.append(seq[1:])

decoder_input = pad_sequences(decoder_input_seq, maxlen=max_len, padding="post")
decoder_output = pad_sequences(decoder_target_seq, maxlen=max_len, padding="post")

embedding_dim = 128
latent_dim = 256

encoder_inputs = Input(shape=(max_len,))
x = Embedding(vocab_size, embedding_dim, mask_zero=True)(encoder_inputs)
encoder_outputs, state_h, state_c = LSTM(latent_dim, return_state=True)(x)

decoder_inputs = Input(shape=(max_len,))
x = Embedding(vocab_size, embedding_dim, mask_zero=True)(decoder_inputs)
decoder_lstm = LSTM(latent_dim, return_sequences=True)
decoder_outputs = decoder_lstm(x, initial_state=[state_h, state_c])

decoder_dense = Dense(vocab_size, activation="softmax")
outputs = decoder_dense(decoder_outputs)

model = Model([encoder_inputs, decoder_inputs], outputs)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

model.fit(
    [encoder_input, decoder_input],
    decoder_output,
    batch_size=32,
    epochs=25
)

reverse_word_index = dict(
    (i, w) for w, i in tokenizer.word_index.items()
)
def translate(text, direction):
    if direction == "eng2banj":
        text = "<2banj> <start> " + text.lower()
    else:
        text = "<2eng> <start> " + text.lower()

    seq = tokenizer.texts_to_sequences([text])
    seq = pad_sequences(seq, maxlen=max_len, padding="post")

    out = model.predict([seq, seq])
    ids = np.argmax(out[0], axis=-1)

    words = []
    for i in ids:
        w = reverse_word_index.get(i, "")
        if w == "<end>" or w == "":
            break
        if w not in ["<start>", "<2banj>", "<2eng>"]:
            words.append(w)

    return " ".join(words)

print(translate("my name can be pronounced same in another language", "eng2banj"))
print(translate("me chango hu", "banj2eng"))